services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: invman
      POSTGRES_PASSWORD: "GVpLSvgYMaDM9KyQx3fG95pUORbNVERo"
    volumes:
      - invman_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "97DXUsmKSlX4dgsOPaEt1QbblFE9fJHo"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: invman_test
      POSTGRES_PASSWORD: "Q3glh2C9bYOtqVMHTvwq-d6DaI8UYaCN"
    volumes:
      - invman_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "e0nMgHYBS-sRcuqS8PLvbFKBqworspBt"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  invman_data:
  invman_test_data:
