# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: 'GVpLSvgYMaDM9KyQx3fG95pUORbNVERo'
  redis: '97DXUsmKSlX4dgsOPaEt1QbblFE9fJHo'

  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: '3sgkGg-OkZCHYgaliZxc0zyQKV0tZe_e'

  emailSecretHashPepper: '-2zewCMTgYxEhgB5N4twXZfldnYOzzP7'
  jwtHmacSha512PrivateKey: 'VTfPFN793NzjI6N01rnAUWJJfN3JVVme'
  jwtRefreshTokenHashPepper: 'WJXOKVlGO84lLD0Sdy4Lc3_OOxMMVF3T'
  # serverSideSessionKeyHashPepper: '4YIOwNiI4Sw3iWfbvW29cZdjNRIvnKxh'

test:
  database: 'Q3glh2C9bYOtqVMHTvwq-d6DaI8UYaCN'
  redis: 'e0nMgHYBS-sRcuqS8PLvbFKBqworspBt'

  emailSecretHashPepper: '7XnZHDG2b6mXTols90qfhFaFIIGxUmrG'
  jwtHmacSha512PrivateKey: 'NLkSiBilWprsNminQkVkF1Izz7WC6CNQ'
  jwtRefreshTokenHashPepper: 'V87tUyGIqsdWiZvwbFIyli06plws1cXL'
  # serverSideSessionKeyHashPepper: '2VfnAt4vq9lmD2b6L6iHq5ysXuDOx5y4'
