apiVersion: v1
kind: ConfigMap
metadata:
  name: rimawari-server-config
  namespace: production
data:
  mailjetApiKeyPublic: "c20de179490741bae3c078d941d67d2f"
  mailjetEmailSender: "noreply@valentinbaudin.ch"

  production.yaml: |
    apiServer:
      port: 8080
      publicHost: api-rimawari.simonbraillard.com
      publicPort: 443
      publicScheme: https

    webServer:
      port: 8082
      publicHost: app-rimawari.kube.simonbraillard.com
      publicPort: 443
      publicScheme: https

    database:
      host: rimawari-postgresql
      port: 5432
      name: serverpod
      user: postgres
      requireSsl: false

    redis:
      enabled: true
      host: rimawari-redis
      port: 6379

    maxRequestSize: 524288

    sessionLogs:
      consoleEnabled: false
