name: App Workflow

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "invman_flutter/**"

env:
  WORK_DIR: invman_flutter
  FLUTTER_VERSION: 3.38.x

jobs:
  unit_tests_and_coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.WORK_DIR}}
    steps:
      - name: 🛠️ Checkout code
        uses: actions/checkout@v3

      - name: ⚙️ Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: ⚙️ Install LCOV
        run: |
          sudo apt-get update
          sudo apt-get -y install lcov

      - name: ▶️ Run tests with coverage
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          dart run intl_utils:generate
          flutter test --coverage

      - name: 📄 Report code coverage
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: invman_flutter/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
          title: "Frontend Coverage Report"

  build:
    if: github.ref == 'refs/heads/main'
    needs: unit_tests_and_coverage
    runs-on: macos-latest 

    defaults:
      run:
        working-directory: ${{env.WORK_DIR}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: ⚙️ Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: 🔑 Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.P12_DIST_CERT }}
          p12-password: ${{ secrets.P12_PASSWORD }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: 📱 Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/distribution.mobileprovision

      - name: Install Dependencies
        run: |
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          dart run intl_utils:generate

      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: Create .env File
        run: |
          echo "BASE_URL=${{ vars.BASE_URL }}" > .env

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          less android/app/keystore.jks
          
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
          less android/key.properties
        
      - name: Build APK
        run: flutter build apk --release --dart-define-from-file .env

      - name: Build appBundle
        run: flutter build appbundle --dart-define-from-file .env
 
      - name: Build IPA
        run: flutter build ipa --release  --dart-define-from-file .env

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            invman_flutter/build/app/outputs/flutter-apk/app-release.apk
            invman_flutter/build/app/outputs/bundle/release/app.aab 
            invman_flutter/build/ios/ipa/*.ipa
          if-no-files-found: error